import { Controller, Get, Query, Res } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import type { Response } from 'express';
import { ConsumptionsService } from '../consumptions.service';
import { ReagentsService } from '../../reagents/reagents.service';
import { ListConsumptionsQueryDto } from '../dto/list-consumptions-query.dto';
import { CurrentUser } from '../../common/decorators/current-user.decorator';
import type { AuthenticatedUser } from '../../common/decorators/current-user.decorator';
import { assertIncludeInactiveAllowed } from '../../common/authorization/assert-include-inactive-allowed';
import { Env } from '../../config/env';
import { exportFilename } from './export-filename';
import { writeConsumptionsWorkbook } from './excel-writer';
import { describeFilters, writeConsumptionsPdf } from './pdf-writer';

const XLSX_TYPE =
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';

@Controller('consumptions')
export class ConsumptionsExportController {
  constructor(
    private readonly consumptions: ConsumptionsService,
    private readonly reagents: ReagentsService,
    private readonly config: ConfigService<Env, true>,
  ) {}

  @Get('export.xlsx')
  async exportXlsx(
    @Query() query: ListConsumptionsQueryDto,
    @CurrentUser() actor: AuthenticatedUser,
    @Res() response: Response,
  ): Promise<void> {
    const isAdmin = actor.role === 'ADMIN';
    assertIncludeInactiveAllowed(query.includeVoided, actor.role);

    // Everything that can fail happens before a byte is written. Taking over
    // the response with @Res() opts this handler out of Nest's exception
    // filter, so a throw after the headers are sent cannot become a status
    // code — it reaches the user as a truncated file that opens cleanly.
    const rows = await this.consumptions.selectForExport(query, isAdmin);
    const filename = exportFilename('xlsx', query, new Date());

    response.setHeader('Content-Type', XLSX_TYPE);
    response.setHeader(
      'Content-Disposition',
      `attachment; filename="${filename}"`,
    );

    await writeConsumptionsWorkbook(
      rows,
      isAdmin && query.includeVoided === true,
      response,
    );
  }

  @Get('export.pdf')
  async exportPdf(
    @Query() query: ListConsumptionsQueryDto,
    @CurrentUser() actor: AuthenticatedUser,
    @Res() response: Response,
  ): Promise<void> {
    const isAdmin = actor.role === 'ADMIN';
    assertIncludeInactiveAllowed(query.includeVoided, actor.role);

    // Same ordering as exportXlsx and for the same reason: everything that
    // can fail — the row-count gate, the reagent-name lookup for the
    // header — happens before a header or byte is written, so a rejection
    // reaches the client as a JSON 400 rather than a truncated PDF.
    const rows = await this.consumptions.selectForExport(query, isAdmin);
    const reagentName = query.reagentId
      ? (await this.reagents.findOne(query.reagentId, isAdmin)).name
      : null;
    const filename = exportFilename('pdf', query, new Date());

    response.setHeader('Content-Type', 'application/pdf');
    response.setHeader(
      'Content-Disposition',
      `attachment; filename="${filename}"`,
    );

    writeConsumptionsPdf(
      rows,
      {
        labName: this.config.get('LAB_NAME', { infer: true }),
        period: periodLabel(query),
        filters: describeFilters(query, reagentName),
        // Never from the query: a client-supplied "generated by" is just
        // text the client chose. This is why the report is built here
        // rather than in the browser.
        generatedBy: actor.fullName,
        generatedAt: new Date(),
      },
      response,
    );
  }
}

function periodLabel(query: ListConsumptionsQueryDto): string {
  const day = (iso: string) => iso.slice(0, 10);
  if (query.from && query.to) {
    return `${day(query.from)} a ${day(query.to)}`;
  }
  if (query.from) {
    return `Desde ${day(query.from)}`;
  }
  if (query.to) {
    return `Hasta ${day(query.to)}`;
  }
  return 'Todo el histórico';
}
